export const SEARCH_STATION = "SEARCH_STATION";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SELECT_CONNECTOR = "SELECT_CONNECTOR";
export const CHANGE_DATE = "CHANGE_DATE";
export const CHANGE_INPUT = "CHANGE_INPUT";
export const SELECT_ENTRIES = "SELECT_ENTRIES";
export const SET_LODER = "SET_LODER";